// Lightweight exporters: Excel (CSV) and a printable investor one-pager.

function egp(v) {
    if (v == null || isNaN(v)) return '';
    return 'E£' + Math.round(Number(v)).toLocaleString();
}

/** #8 Export the business summary to a CSV file (opens in Excel). */
export function exportExcel(config = {}, summary = {}) {
    const name = config.businessName || config.projectName || 'Business';
    const rows = [
        ['Business Digital Twin — Export'],
        ['Business', name],
        ['Type', config.businessType || ''],
        ['Location', config.location || ''],
        [],
        ['Metric', 'Value'],
        ['Monthly Revenue', egp(summary.monthlyRevenue)],
        ['Monthly Profit', egp(summary.monthlyProfit)],
        ['Profit Margin (%)', summary.profitMargin ?? ''],
        ['Startup Capital', egp(summary.startup?.total ?? summary.startup)],
        ['Annual Revenue', egp(summary.annualRevenue)],
        ['Annual Profit', egp(summary.annualProfit)],
        ['Break-Even (month)', summary.breakEven?.month ?? ''],
        ['ROI (%)', summary.roi?.roi ?? summary.roi ?? ''],
        [],
        ['Configuration', ''],
        ['Rent', egp(config.rent)],
        ['Employees', config.employees ?? ''],
        ['Avg Salary', egp(config.avgSalary)],
        ['Avg Ticket', egp(config.avgTicket)],
        ['Daily Customers', config.dailyCustomers ?? ''],
        ['Sq Ft', config.sqft ?? ''],
        ['Equipment Cost', egp(config.equipmentCost)],
    ];
    const csv = '﻿' + rows.map(r => r.map(c => {
        const s = String(c ?? '');
        return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
    }).join(',')).join('\n');

    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${name.replace(/[^a-z0-9]+/gi, '_')}_BusinessTwin.csv`;
    document.body.appendChild(a); a.click(); a.remove();
    URL.revokeObjectURL(url);
}

/** #10 Open a clean, printable investor one-pager (user can Save as PDF). */
export function openInvestorOnePager(config = {}, summary = {}, risks = {}) {
    const name = config.businessName || config.projectName || 'Business Twin';
    const riskScore = risks?.riskScore?.score ?? risks?.riskScore ?? '—';
    const kpi = (label, val) => `<div class="kpi"><div class="v">${val}</div><div class="l">${label}</div></div>`;
    const html = `<!doctype html><html><head><meta charset="utf-8"><title>${name} — Investor One-Pager</title>
    <style>
      *{box-sizing:border-box;font-family:Arial,Helvetica,sans-serif}
      body{margin:0;padding:40px;color:#0f172a}
      h1{margin:0 0 4px;font-size:28px}
      .sub{color:#64748b;margin-bottom:24px}
      .grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-bottom:28px}
      .kpi{border:1px solid #e2e8f0;border-radius:12px;padding:18px}
      .kpi .v{font-size:24px;font-weight:800}
      .kpi .l{font-size:11px;color:#64748b;text-transform:uppercase;letter-spacing:.08em;margin-top:4px}
      .foot{margin-top:32px;color:#94a3b8;font-size:11px;border-top:1px solid #e2e8f0;padding-top:12px}
      @media print{body{padding:24px}}
    </style></head><body>
      <h1>${name}</h1>
      <div class="sub">${config.businessType || ''} · ${config.location || ''} · Business Digital Twin</div>
      <div class="grid">
        ${kpi('Monthly Revenue', egp(summary.monthlyRevenue) || '—')}
        ${kpi('Monthly Profit', egp(summary.monthlyProfit) || '—')}
        ${kpi('Profit Margin', summary.profitMargin != null ? summary.profitMargin + '%' : '—')}
        ${kpi('Startup Capital', egp(summary.startup?.total ?? summary.startup) || '—')}
        ${kpi('Annual Revenue', egp(summary.annualRevenue) || '—')}
        ${kpi('Annual Profit', egp(summary.annualProfit) || '—')}
        ${kpi('Break-Even', summary.breakEven?.month != null ? 'Month ' + summary.breakEven.month : '—')}
        ${kpi('ROI', (summary.roi?.roi ?? summary.roi) != null ? (summary.roi?.roi ?? summary.roi) + '%' : '—')}
        ${kpi('Risk Score', riskScore + '/100')}
      </div>
      <div class="foot">Generated by Business Digital Twin · ${new Date().toLocaleDateString()}</div>
      <script>window.onload=()=>{setTimeout(()=>window.print(),300)}<\/script>
    </body></html>`;
    const w = window.open('', '_blank');
    if (w) { w.document.write(html); w.document.close(); }
}
