import React, { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import api from '../lib/api';
import { formatCurrency } from '../engine/SimulationEngine';

/**
 * Read-only investor view of a shared Business Twin — no login required.
 * Reached at /twin/:shareId via a share link generated by the owner.
 */
export default function PublicTwinView() {
    const shareId = window.location.pathname.split('/twin/')[1]?.replace(/\/$/, '');
    const [state, setState] = useState({ loading: true, error: null, data: null });

    useEffect(() => {
        if (!shareId) { setState({ loading: false, error: 'Invalid share link', data: null }); return; }
        api.get(`/public/twin/${shareId}`)
            .then(res => setState({ loading: false, error: null, data: res.data.data }))
            .catch(err => setState({ loading: false, error: err.response?.data?.error || 'Could not load shared twin', data: null }));
    }, [shareId]);

    if (state.loading) {
        return <div className="min-h-screen bg-[#02040a] flex items-center justify-center text-zinc-500 text-sm">Loading shared twin…</div>;
    }
    if (state.error) {
        return (
            <div className="min-h-screen bg-[#02040a] flex items-center justify-center p-6">
                <div className="text-center">
                    <div className="text-5xl mb-4">🔒</div>
                    <div className="text-white text-lg font-bold mb-2">{state.error}</div>
                    <div className="text-zinc-600 text-sm">This investor link may have been revoked by the owner.</div>
                </div>
            </div>
        );
    }

    const p = state.data || {};
    const s = p.summary || {};
    const risk = p.risks || {};
    const riskScore = risk.riskScore?.score ?? risk.riskScore;

    const kpis = [
        { label: 'Monthly Revenue', val: s.monthlyRevenue != null ? formatCurrency(s.monthlyRevenue) : '—' },
        { label: 'Monthly Profit', val: s.monthlyProfit != null ? formatCurrency(s.monthlyProfit) : '—' },
        { label: 'Startup Capital', val: s.startup?.total != null ? formatCurrency(s.startup.total) : (s.startup != null ? formatCurrency(s.startup) : '—') },
        { label: 'Profit Margin', val: s.profitMargin != null ? `${s.profitMargin}%` : '—' },
        { label: 'Break-Even', val: s.breakEven?.month != null ? `Month ${s.breakEven.month}` : '—' },
        { label: 'Risk Score', val: riskScore != null ? `${riskScore}/100` : '—' },
    ];

    return (
        <div className="min-h-screen bg-[#02040a] text-white">
            {/* Read-only banner */}
            <div className="w-full bg-brand-secondary/10 border-b border-brand-secondary/20 py-2 text-center">
                <span className="text-[10px] font-black text-brand-secondary uppercase tracking-[0.3em]">🔒 Read-Only Investor View · Business Digital Twin</span>
            </div>

            <div className="max-w-5xl mx-auto px-6 py-12">
                <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="mb-10">
                    <h1 className="text-3xl font-display font-bold text-white mb-2">{p.businessName || p.projectName || 'Business Twin'}</h1>
                    <p className="text-sm text-zinc-500 capitalize">{p.businessType || '—'} · {p.location || '—'}</p>
                </motion.div>

                <div className="grid grid-cols-2 md:grid-cols-3 gap-5 mb-12">
                    {kpis.map((k, i) => (
                        <motion.div
                            key={k.label}
                            initial={{ opacity: 0, y: 12 }}
                            animate={{ opacity: 1, y: 0 }}
                            transition={{ delay: i * 0.05 }}
                            className="p-6 rounded-2xl bg-white/[0.02] border border-white/8"
                        >
                            <div className="text-2xl font-display font-black text-white mb-1">{k.val}</div>
                            <div className="text-[10px] font-bold text-zinc-600 uppercase tracking-widest">{k.label}</div>
                        </motion.div>
                    ))}
                </div>

                {Array.isArray(p.insights) && p.insights.length > 0 && (
                    <div className="rounded-2xl bg-white/[0.02] border border-white/8 p-8">
                        <div className="text-[10px] font-black text-brand-primary uppercase tracking-[0.2em] mb-5">AI Insights</div>
                        <div className="space-y-4">
                            {p.insights.slice(0, 5).map((ins, i) => (
                                <div key={i} className="flex gap-3">
                                    <span className="text-brand-primary">▪</span>
                                    <p className="text-sm text-zinc-300 leading-relaxed">
                                        {typeof ins === 'string' ? ins : (ins.title || ins.description || ins.message || JSON.stringify(ins))}
                                    </p>
                                </div>
                            ))}
                        </div>
                    </div>
                )}

                <div className="mt-12 text-center text-[10px] text-zinc-700 uppercase tracking-widest">
                    Generated by Business Digital Twin · Shared by the business owner
                </div>
            </div>
        </div>
    );
}
